### ISSUE TITLE
Test suite failing on CI

### ISSUE THREAD

**Issue by znck** [vuejs/component-compiler-utils#34]
``` log
#!/bin/bash -eo pipefail
yarn test
yarn run v1.6.0
$ prettier --list-different "{lib,test}/**/*.ts" && jest --coverage
 FAIL  test/compileStyle.spec.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at Array.forEach (native)

 FAIL  test/stylePluginScoped.spec.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at Array.forEach (native)

 FAIL  test/compileTemplate.spec.ts
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins
      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
      at Array.forEach (native)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        1.225s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by yyx990803** [comment]
Caused by https://github.com/facebook/jest/issues/6766, fixed
